name: Publish to pkg.pr.new
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Prepare development build
        run: pnpm dev:prepare

      - name: Test code
        run: pnpm test

      - name: Build packages
        run: pnpm build

      - name: Publish to pkg.pr.new
        run: pnpx pkg-pr-new publish --comment=update
